### ISSUE TITLE
Coverage for Negation Aliases

### ISSUE THREAD

**Issue by jkotanchik-SB** [projecttacoma/fqm-execution#287]
### Summary

Another round of Measures experiencing issues reaching 100% coverage. It may be an extension of #285 and I move these materials to that issue if it makes sense. 

The potential difference being the problematic aliases deal with negation, if that's a difference at all.

Impacted Measures:
1. **CMS 2 Preventive Care and Screening: Screening for Depression and Follow-Up PlanFHIR**

2. **CMS 22 Preventive Care and Screening: Screening for High Blood Pressure and Follow-Up DocumentedFHIR**

3. **CMS69 Preventive Care and Screening: Body Mass Index (BMI) Screening and Follow-Up PlanFHIR**

4. **CMS347 Statin Therapy for the Prevention and Treatment of Cardiovascular DiseaseFHIR**

#### External Tracking Ticket
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1631

### Expected Behavior
100% coverage

### Version or Commit
v1.3.1

### Inputs (e.g. Measure Bundle, Patient Bundle, CQL Library)
Measure Bundles:
1. [CMS2FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13044977/CMS2FHIR-v0.2.000-FHIR4.zip)
2. [CMS22FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13044976/CMS22FHIR-v0.2.000-FHIR4.zip)
3. [CMS69FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13044975/CMS69FHIR-v0.2.000-FHIR4.zip)
4. [CMS347FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13044972/CMS347FHIR-v0.2.000-FHIR4.zip)

MADiE Patient Exports:
1. [CMS2FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13044988/CMS2FHIR-v0.2.000-FHIR4-TestCases.zip)
2. [CMS22FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13044987/CMS22FHIR-v0.2.000-FHIR4-TestCases.zip)
3. [CMS69FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13044986/CMS69FHIR-v0.2.000-FHIR4-TestCases.zip)
4. [CMS347FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13044985/CMS347FHIR-v0.2.000-FHIR4-TestCases.zip)

### Relevant Calculation Options (e.g. Measurement Period, meta.profile Validation)
```
{
    includeClauseResults: false,
    trustMetaProfile: true,
    buildStatementLevelHTML: true,
    measurementPeriodStart: 1/1/2025,
    measurementPeriodEnd: 12/31/2025,
}
```
### cql-to-elm Version Used for Measure Logic Translation (if known)
`v2.11.0`

### Any Additional Info

**Comment by hossenlopp** [comment]
Hi @jkotanchik-SB,

The aliases, unions and library references that visually show as uncovered do not affect coverage percentage calculations. These are caused by quirks in the ELM annotations.

We have just released [v1.3.2](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.3.2) which fixes an issue with visual coverage and should now properly show locations in the logic that are uncovered in many cases. This update should make it clear where those last few uncovered clauses are and aid in creating additional test cases.

Please test with this release and open a new issue if there are additional problems with coverage or you are unable to get to 100% after satisfying the clauses that will now properly show as uncovered.

**Comment by sb-cecilialiu** [comment]
@hossenlopp Good afternoon! We tested the newly released v1.3.2 but it seems the issues are still not resolved. I'm attaching the measures and test cases for the testing of the issue for your reference, hopefully this issue can be re-opened soon and looked into. Thanks!
[CMS2FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13312312/CMS2FHIR-v0.2.000-FHIR4-TestCases.zip)
[CMS2FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13312313/CMS2FHIR-v0.2.000-FHIR4.zip)
[CMS22FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13312315/CMS22FHIR-v0.2.000-FHIR4-TestCases.zip)
[CMS22FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13312316/CMS22FHIR-v0.2.000-FHIR4.zip)
[CMS69FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13312318/CMS69FHIR-v0.2.000-FHIR4-TestCases.zip)
[CMS69FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13312319/CMS69FHIR-v0.2.000-FHIR4.zip)
[CMS347FHIR-v0.2.000-FHIR4-TestCases.zip](https://github.com/projecttacoma/fqm-execution/files/13312320/CMS347FHIR-v0.2.000-FHIR4-TestCases.zip)
[CMS347FHIR-v0.2.000-FHIR4.zip](https://github.com/projecttacoma/fqm-execution/files/13312321/CMS347FHIR-v0.2.000-FHIR4.zip)

**Comment by elsaperelli** [comment]
The issue with coverage percentage calculation for the `!~` (Not Equivalent) clause in CMS69 was fixed in #291 and released in [fqm-execution 1.3.3](https://github.com/projecttacoma/fqm-execution/releases/tag/v1.3.3). The coverage calculation percentage was not reaching 100% due to how the cql-to-elm translator currently translates this CQL. This also accounts for potential translator changes for `!=` (Not Equal). The attached document goes into more detail on this issue.

[fqm-execution Not Equivalent Handling.pdf](https://github.com/projecttacoma/fqm-execution/files/13719660/fqm-execution.Not.Equivalent.Handling.pdf)

**Comment by elsaperelli** [comment]
Hi @sb-cecilialiu  @jkotanchik-SB 

Our team has looked into CMS347 and was able to get 100% clause coverage for each of the four population groups with additional test cases. The clause coverage highlighting reflects the 100% clause coverage, with the exception of aliases, unions and library references that visually show as uncovered but do not affect coverage percentage calculations. As previously mentioned, these are caused by quirks in the ELM annotations. 

Thank you!

**Comment by sb-cecilialiu** [comment]
@elsaperelli Thank you so much!
